// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyPyJiXqovVzm3wLHRVc4nt4NpQKZOjQM',
    appId: '1:86184796911:web:8d77cf4936a514cf33711a',
    messagingSenderId: '86184796911',
    projectId: 'xian-8c58c',
    authDomain: 'xian-8c58c.firebaseapp.com',
    storageBucket: 'xian-8c58c.appspot.com',
    measurementId: 'G-PLKPMRW3S6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7vQFWnED0wI5H5cxyKjOSRq1sAXaJBQI',
    appId: '1:86184796911:android:c679f10571050fdf33711a',
    messagingSenderId: '86184796911',
    projectId: 'xian-8c58c',
    storageBucket: 'xian-8c58c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1F6mYM4oS-PFmy-olZG77Rm_nY64QBug',
    appId: '1:86184796911:ios:ddd07ae113d7c9e833711a',
    messagingSenderId: '86184796911',
    projectId: 'xian-8c58c',
    storageBucket: 'xian-8c58c.appspot.com',
    iosBundleId: 'com.example.xianinfotech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1F6mYM4oS-PFmy-olZG77Rm_nY64QBug',
    appId: '1:86184796911:ios:ddd07ae113d7c9e833711a',
    messagingSenderId: '86184796911',
    projectId: 'xian-8c58c',
    storageBucket: 'xian-8c58c.appspot.com',
    iosBundleId: 'com.example.xianinfotech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyPyJiXqovVzm3wLHRVc4nt4NpQKZOjQM',
    appId: '1:86184796911:web:e64bdd0204f8057833711a',
    messagingSenderId: '86184796911',
    projectId: 'xian-8c58c',
    authDomain: 'xian-8c58c.firebaseapp.com',
    storageBucket: 'xian-8c58c.appspot.com',
    measurementId: 'G-G050HKDGXJ',
  );
}
